//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<thermallogistics:manager:1>);
recipes.remove(<thermallogistics:manager>);
recipes.remove(<thermalexpansion:machine:7>);
recipes.remove(<patchouli:guide_book>);
recipes.remove(<thermalfoundation:glass_alloy:7>);
recipes.remove(<thermalfoundation:glass_alloy:6>);
recipes.remove(<thermalfoundation:glass_alloy:5>);
recipes.remove(<thermalfoundation:glass_alloy:4>);
recipes.remove(<thermalfoundation:glass_alloy:3>);
recipes.remove(<thermalfoundation:glass_alloy:2>);
recipes.remove(<thermalfoundation:glass_alloy:1>);
recipes.remove(<thermalfoundation:glass_alloy>);
recipes.remove(<thermalfoundation:glass:8>);
recipes.remove(<thermalfoundation:glass:7>);
recipes.remove(<thermalfoundation:glass:6>);
recipes.remove(<thermalfoundation:glass:5>);
recipes.remove(<thermalfoundation:glass:4>);
recipes.remove(<thermalfoundation:glass:2>);
recipes.remove(<thermalfoundation:glass:1>);
recipes.remove(<thermalfoundation:glass>);
recipes.remove(<thermalfoundation:material:97>);
recipes.remove(<thermalfoundation:material:98>);
recipes.remove(<thermalexpansion:machine:6>);
recipes.remove(<thermalexpansion:machine:7>);
recipes.remove(<thermalexpansion:capacitor>);
//recipes.remove(<whoosh:transporter>);
//recipes.remove(<whoosh:transporter:1>);
//recipes.remove(<whoosh:transporter:2>);
recipes.remove(<whoosh:transporter>);
recipes.remove(<ironjetpacks:plastic_jetpack>);
recipes.remove(<chickenchunks:chunk_loader>);
recipes.remove(<ultimatecobblegen:cobblegenerator>);
recipes.remove(<minecraft:diamond_shovel>);
//recipes.remove(<thermalcultivation:watering_can:2>);
//recipes.remove(<thermalcultivation:watering_can:1>);
//recipes.remove(<thermalinnovation:magnet:2>);
//recipes.remove(<thermalinnovation:magnet:1>);
//recipes.remove(<thermalinnovation:drill:2>);
//recipes.remove(<thermalinnovation:drill:1>);
recipes.remove(<matteroverdrive:phaser_rifle>);
recipes.remove(<inventorygenerators:inv_survivalist_gen>);
recipes.remove(<ironjetpacks:plastic_jetpack>);
recipes.remove(<environmentaltech:diode>);
recipes.remove(<mekanism:machineblock3:6>);
recipes.remove(<matteroverdrive:plasma_shotgun>);
recipes.remove(<matteroverdrive:phaser>);
recipes.remove(<thermalinnovation:saw>);
recipes.remove(<thermalinnovation:magnet>);
recipes.remove(<thermalinnovation:drill>);
recipes.remove(<thermalfoundation:material:656>);
recipes.remove(<danknull:dank_null_panel:0>);
recipes.remove(<ironjetpacks:plastic_cell>);
recipes.remove(<ironjetpacks:plastic_thruster>);
recipes.remove(<minecraft:paper>);
recipes.remove(<extraplanets:tools:2>);
recipes.remove(<scannable:module_ore_rare>);
recipes.remove(<scannable:module_blank>);
recipes.remove(<powersuits:power_fist>);
recipes.remove(<galacticraftplanets:orion_drive>);
recipes.remove(<environmentaltech:structure_frame_1>);
recipes.remove(<mekanism:machineblock:8>);
recipes.remove(<galacticraftplanets:mars_machine_t2:4>);
recipes.remove(<galacticraftcore:machine2>);
recipes.remove(<galacticraftcore:aluminum_wire>);
recipes.remove(<galacticraftcore:machine_tiered:12>);
recipes.remove(<galacticraftcore:machine_tiered:4>);
recipes.remove(<mekanism:basicblock2:6>);
recipes.remove(<mekanism:basicblock2:8> * 2);
recipes.remove(<mekanism:basicblock:15>);
recipes.remove(<mekanism:basicblock:14>);
recipes.remove(<minestrapp:m_plating:6>);
recipes.remove(<minestrapp:iron_dagger>);
recipes.remove(<moreplanets:space_portal>);
recipes.remove(<rftools:shape_card:2>);
recipes.remove(<minecraft:diamond_pickaxe>);
recipes.remove(<minecraft:diamond_hoe>);
recipes.remove(<minecraft:diamond_axe>);
recipes.remove(<minecraft:diamond_shovel>);
recipes.remove(<minecraft:diamond_sword>);
recipes.remove(<minecraft:diamond_shovel>);
recipes.remove(<moreplanets:space_warper_core>);
recipes.remove(<exnihilocreatio:item_material:6>);
recipes.remove(<inventorygenerators:inv_end_gen>);
recipes.remove(<inventorygenerators:inv_halitosis_gen>);
recipes.remove(<inventorygenerators:inv_nether_star_gen>);
recipes.remove(<inventorygenerators:inv_potion_gen>);
recipes.remove(<simplegenerators:culinary_simple>);
recipes.remove(<simplegenerators:ender_simple>);
recipes.remove(<simplegenerators:geothermal_simple>);
recipes.remove(<simplegenerators:fluid_combustion_simple>);
recipes.remove(<simplegenerators:soul_simple>);
recipes.remove(<simplegenerators:nether_simple>);
recipes.remove(<simplegenerators:combustion_simple>);
recipes.remove(<inventorygenerators:inv_overclocked_gen>);
recipes.remove(<inventorygenerators:inv_culinary_gen>);
recipes.remove(<inventorygenerators:inv_explosive_gen>);
recipes.remove(<inventorygenerators:inv_pink_gen>);
recipes.remove(<inventorygenerators:inv_frosty_gen>);
recipes.remove(<inventorygenerators:inv_death_gen>);
recipes.remove(<inventorygenerators:inv_slimey_gen>);
recipes.remove(<valkyrielib:modifier_component>);
recipes.remove(<moreplanets:space_warp_pad>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<extraplanets:tier1_space_suit_jetpack_chest:100>);
recipes.remove(<powersuits:powerarmor_feet>);
recipes.remove(<powersuits:powerarmor_legs>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_head>);
recipes.remove(<galacticraftcore:machine:12>);
recipes.remove(<mekanismgenerators:generator:6>);
recipes.remove(<deepmoblearning:glitch_infused_boots>);
recipes.remove(<deepmoblearning:glitch_infused_boots>);
recipes.remove(<deepmoblearning:glitch_infused_leggings>);
recipes.remove(<deepmoblearning:glitch_infused_helmet>);
recipes.remove(<deepmoblearning:glitch_infused_chestplate>);
recipes.remove(<mekanism:configurator>);
recipes.remove(<minecraft:hopper>);
recipes.remove(<galacticraftcore:fluid_tank>);
recipes.remove(<mekanism:jetpack>);
recipes.remove(<lcrdrfs:jetpack>);
recipes.removeShaped(<slabmachines:furnace_slab>);
recipes.remove(<minecraft:dirt>);
recipes.remove(<galacticraftcore:rocket_workbench>);
recipes.remove(<mekanism:machineblock:11>);
recipes.remove(<mekanism:basicblock:8>);
recipes.remove(<mekanism:machineblock:4>);
recipes.remove(<mekanism:basicblock2> * 4);
recipes.remove(<mekanism:basicblock2:7> * 4);
recipes.remove(<rftools:machine_frame>);
recipes.remove(<rftools:matter_receiver>);
recipes.remove(<rftools:matter_transmitter>);
recipes.remove(<rftools:matter_transmitter>);
recipes.remove(<galacticraftplanets:item_basic_mars:6>);
recipes.remove(<galacticraftplanets:carbon_fragments>);
recipes.remove(<deepmoblearning:trial_keystone>);
recipes.remove(<simplegenerators:nether_simple>);
recipes.remove(<industrialforegoing:material_stonework_factory>);
recipes.remove(<ultimatecobblegen:dustgenerator>);
recipes.remove(<appliedenergistics2:wireless_terminal>);
recipes.remove(<wct:wct>);
recipes.remove(<ultimatecobblegen:fungusgenerator>);
recipes.remove(<ultimatecobblegen:obsidiangenerator>);
recipes.remove(<ultimatecobblegen:snowgenerator>);
recipes.remove(<ultimatecobblegen:icegenerator>);
recipes.remove(<ultimatecobblegen:grassgenerator>);
recipes.remove(<ultimatecobblegen:gravelgenerator>);
recipes.remove(<matteroverdrive:replicator>);
recipes.remove(<matteroverdrive:decomposer>);
recipes.remove(<matteroverdrive:matter_analyzer>);
recipes.remove(<storagenetwork:master>);
recipes.remove(<appliedenergistics2:material:38>);
recipes.remove(<appliedenergistics2:material:37>);
recipes.remove(<appliedenergistics2:material:36>);
recipes.remove(<appliedenergistics2:material:35>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<minecraft:furnace>);
recipes.remove(<galacticraftcore:refinery>);
recipes.remove(<extraplanets:tier1_space_suit_boots>);
recipes.remove(<extraplanets:tier1_space_suit_legings>);
recipes.remove(<extraplanets:tier1_space_suit_chest>);
recipes.remove(<extraplanets:tier1_space_suit_helmet>);
recipes.remove(<extraplanets:tier1_radiation_layer>);
recipes.remove(<minestrapp:m_tech_component> * 8);
//recipes.remove(<galacticraftcore:refinery>);
//recipes.remove(<teslathingies:crop_cloner>);
recipes.remove(<extraplanets:tier1_space_suit_boots:100>);
recipes.remove(<extraplanets:tier1_space_suit_legings:100>);
recipes.remove(<extraplanets:tier1_space_suit_chest:100>);
recipes.remove(<extraplanets:tier1_space_suit_helmet:100>);
recipes.remove(<galacticraftcore:basic_item:19>);
recipes.remove(<scannable:scanner>);
recipes.remove(<extraplanets:anti_radiation>);
recipes.remove(<exnihilocreatio:block_end_cake>);
recipes.remove(<storagenetwork:kabel>);
//Don't touch me!
//#Add
recipes.addShaped(<thermalfoundation:material:65> * 2, [[null, null, null],[null, null, null], [null, <ore:dustIron>, <ore:dustAluminum>]]);
recipes.addShaped(<thermallogistics:manager:1>, [[null, <minecraft:iron_nugget>, null],[<thermalfoundation:material:162>, <thermallogistics:manager>, <thermalfoundation:material:162>], [<minecraft:iron_nugget>, null, <minecraft:iron_nugget>]]);
recipes.addShaped(<thermallogistics:manager>, [[<minecraft:iron_nugget>, <minecraft:redstone_torch>, <minecraft:iron_nugget>],[<minecraft:iron_nugget>, <thermalfoundation:material:640>, <minecraft:iron_nugget>], [<minecraft:iron_nugget>, <ore:dustSulfur>, <minecraft:iron_nugget>]]);
recipes.addShaped(<moreplanets:space_warp_pad>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <matteroverdrive:tritanium_plate>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<galacticraftplanets:desh_pick_slime>, [[<minecraft:slime_ball>, <minecraft:slime_ball>, <minecraft:slime_ball>],[null, <galacticraftplanets:desh_pick>, null], [null, null, null]]);
recipes.addShaped(<galacticraftplanets:orion_drive>, [[<galacticraftcore:basic_item:9>, <galacticraftplanets:item_basic_mars:3>, <galacticraftcore:basic_item:9>],[null, <galacticraftplanets:item_basic_asteroids:8>, null], [<galacticraftcore:steel_pole>, null, <galacticraftcore:steel_pole>]]);
recipes.addShaped(<mekanism:machineblock:4>, [[<matteroverdrive:tritanium_plate>, <galacticraftplanets:item_basic_mars:3>, <matteroverdrive:tritanium_plate>],[<galacticraftplanets:item_basic_mars:3>, <galacticraftplanets:astro_miner>, <galacticraftplanets:item_basic_mars:3>], [<matteroverdrive:tritanium_plate>, <galacticraftplanets:item_basic_mars:3>, <matteroverdrive:tritanium_plate>]]);
recipes.addShapeless(<exnihilocreatio:item_material:6> * 2, [<minecraft:cobblestone>,<minecraft:cobblestone>]);
recipes.addShaped(<thermalexpansion:machine:7>, [[<thermalexpansion:tank>, <ore:gearCopper>, <thermalexpansion:tank>],[<ore:blockGlassColorless>, <thermalexpansion:frame>, <ore:blockGlassColorless>], [<ore:gearCopper>, <thermalfoundation:material:513>, <ore:gearCopper>]]);
recipes.addShaped(<minecraft:paper> * 6, [[null, null, null],[<ore:dustWood>, <ore:dustWood>, <ore:dustWood>], [<ore:dustWood>, <ore:dustWood>, <ore:dustWood>]]);
recipes.addShapeless(<galacticraftplanets:basic_item_venus:4> * 2, [<ore:dustGold>,<ore:dustIron>,<ore:dustElectrum>,<ore:dustCopper>]);
recipes.addShapeless(<patchouli:guide_book>.withTag({"patchouli:book": "deepmoblearning:book"}), [<minecraft:book>,<minecraft:redstone>,<minestrapp:m_gem:6>]);
recipes.addShapeless(<thermalfoundation:material:64>, [<minecraft:redstone>,<ore:dustIron>]);
recipes.addShapeless(<minecraft:leather>, [<minestrapp:m_leather:13>]);
recipes.addShapeless(<thermalfoundation:material:866>, [<ore:dustGold>,<minecraft:redstone>]);
recipes.addShaped(<galacticraftcore:aluminum_wire> * 2, [[null, null, null],[<ore:ingotAluminum>, <galacticraftcore:basic_item:11>, <ore:ingotAluminum>], [null, null, null]]);
recipes.addShaped(<thermalfoundation:material:97> * 2, [[<ore:dustGold>, <ore:dustIron>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:material:98> * 3, [[<ore:dustIron>, <ore:dustIron>, null],[<ore:dustTin>, null, null], [null, null, null]]);
recipes.addShaped(<thermalexpansion:machine:6>, [[null, <thermalexpansion:tank>, null],[<minecraft:nether_brick>, <thermalexpansion:frame>, <minecraft:nether_brick>], [<galacticraftcore:basic_item:14>, <thermalfoundation:material:513>, <galacticraftcore:basic_item:14>]]);
recipes.addShaped(<thermalexpansion:machine:7>, [[<thermalexpansion:tank>, <thermalfoundation:material:292>, <thermalexpansion:tank>],[<minecraft:glass>, <thermalexpansion:frame>, <minecraft:glass>], [<thermalfoundation:material:292>, <thermalfoundation:material:513>, <thermalfoundation:material:292>]]);
recipes.addShaped(<thermalexpansion:capacitor>, [[null, <minecraft:redstone>, null],[<galacticraftcore:basic_item:4>, <galacticraftcore:basic_item:14>, <galacticraftcore:basic_item:4>], [<minecraft:redstone>, <galacticraftcore:basic_item:9>, <minecraft:redstone>]]);
recipes.addShaped(<whoosh:transporter>, [[null, <ore:paneGlassColorless>, null],[<thermalfoundation:material:24>, <thermalfoundation:material:513>, <thermalfoundation:material:24>], [<galacticraftcore:basic_item:11>, <minecraft:iron_ingot>, <galacticraftcore:basic_item:11>]]);
recipes.addShaped(<thermalinnovation:drill>, [[null, <thermalfoundation:material:656>, null],[<minecraft:iron_ingot>, <thermalfoundation:material:640>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <thermalfoundation:material:24>, <minecraft:iron_ingot>]]);
recipes.addShaped(<thermalinnovation:magnet>, [[<minecraft:redstone>, null, <minecraft:redstone>],[<galacticraftcore:basic_item:11>, null, <galacticraftcore:basic_item:11>], [<galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:11>]]);
recipes.addShaped(<thermalinnovation:saw>, [[null, <thermalfoundation:material:657>, null],[<minecraft:iron_ingot>, <thermalfoundation:material:640>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <thermalfoundation:material:24>, <minecraft:iron_ingot>]]);
recipes.addShaped(<thermalfoundation:material:656>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, null],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [null, <minecraft:iron_ingot>, <galacticraftcore:basic_item:11>]]);
recipes.addShaped(<chickenchunks:chunk_loader>, [[null, <extraplanets:wafer>, null],[<galacticraftcore:heavy_plating>, <opencomputers:upgrade:4>, <galacticraftcore:heavy_plating>], [<galacticraftplanets:item_basic_mars:3>, <ironjetpacks:steel_capacitor>, <galacticraftplanets:item_basic_mars:3>]]);
recipes.addShaped(<ultimatecobblegen:cobblegenerator>, [[<galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:8>, <galacticraftcore:basic_item:9>],[<minecraft:lava_bucket>, <minecraft:iron_pickaxe>, <minecraft:water_bucket>], [<galacticraftcore:basic_item:6>, <galacticraftcore:basic_item:7>, <galacticraftcore:basic_item:10>]]);
recipes.addShaped(<minecraft:diamond_shovel>, [[null, <minecraft:diamond>, null],[null, <minestrapp:m_tech_component>, null], [null, <minestrapp:m_tech_component>, null]]);
recipes.addShaped(<matteroverdrive:phaser>, [[null, null, null],[<thermalfoundation:material:640>, <thermalfoundation:material:24>, <galacticraftcore:basic_item:11>], [<ironjetpacks:diamond_cell>, null, null]]);
recipes.addShaped(<inventorygenerators:inv_survivalist_gen>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <galacticraftcore:basic_item:11>, <minecraft:iron_ingot>], [<minecraft:redstone>, <slabmachines:furnace_slab>, <minecraft:redstone>]]);
recipes.addShaped(<environmentaltech:diode>, [[<extraplanets:tier10_items:5>, <extraplanets:tier10_items:5>, <extraplanets:tier10_items:5>],[<extraplanets:tier10_items:5>, <minecraft:redstone>, <extraplanets:tier10_items:5>], [<extraplanets:tier10_items:5>, <minecraft:redstone>, <extraplanets:tier10_items:5>]]);
recipes.addShaped(<mekanism:machineblock3:6>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:13>, <galacticraftcore:basic_item:9>],[<minecraft:furnace>, <mekanism:basicblock:8>, <minecraft:furnace>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<mekanism:machineblock:8>, [[<matteroverdrive:tritanium_ingot>, <minecraft:furnace>, <matteroverdrive:tritanium_ingot>],[<minecraft:redstone>, <galacticraftcore:basic_item:14>, <minecraft:redstone>], [<matteroverdrive:tritanium_ingot>, <minecraft:furnace>, <matteroverdrive:tritanium_ingot>]]);
recipes.addShaped(<matteroverdrive:phaser_rifle>, [[null, null, null],[<thermalfoundation:material:640>, <ironjetpacks:diamond_capacitor>, <galacticraftcore:steel_pole>], [<ironjetpacks:steel_capacitor>, null, null]]);
recipes.addShaped(<matteroverdrive:plasma_shotgun>, [[null, null, null],[<thermalfoundation:material:640>, <ironjetpacks:diamond_capacitor>, <galacticraftcore:steel_pole>], [<ironjetpacks:meteoric_capacitor>, null, null]]);
recipes.addShaped(<matteroverdrive:phaser>, [[null, null, null],[<thermalfoundation:material:640>, <thermalfoundation:material:24>, <galacticraftcore:basic_item:11>], [<ironjetpacks:steel_cell>, null, null]]);
recipes.addShaped(<danknull:dank_null_panel:0>, [[<galacticraftplanets:asteroids_block:2>, <galacticraftplanets:asteroids_block:2>, <galacticraftplanets:asteroids_block:2>],[<galacticraftplanets:asteroids_block:2>, <minecraft:redstone>, <galacticraftplanets:asteroids_block:2>], [<galacticraftplanets:asteroids_block:2>, <galacticraftplanets:asteroids_block:2>, <galacticraftplanets:asteroids_block:2>]]);
recipes.addShaped(<danknull:dank_null_panel>, [[<galacticraftplanets:asteroids_block:1>, <galacticraftplanets:asteroids_block:1>, <galacticraftplanets:asteroids_block:1>],[<galacticraftplanets:asteroids_block:1>, <minecraft:redstone>, <galacticraftplanets:asteroids_block:1>], [<galacticraftplanets:asteroids_block:1>, <galacticraftplanets:asteroids_block:1>, <galacticraftplanets:asteroids_block:1>]]);
recipes.addShaped(<danknull:dank_null_panel>, [[<galacticraftplanets:asteroids_block>, <galacticraftplanets:asteroids_block>, <galacticraftplanets:asteroids_block>],[<galacticraftplanets:asteroids_block>, <minecraft:redstone>, <galacticraftplanets:asteroids_block>], [<galacticraftplanets:asteroids_block>, <galacticraftplanets:asteroids_block>, <galacticraftplanets:asteroids_block>]]);
recipes.addShaped(<ironjetpacks:plastic_cell>, [[null, <minecraft:redstone>, null],[null, <industrialforegoing:plastic>, null], [null, <industrialforegoing:plastic>, null]]);
recipes.addShaped(<ironjetpacks:plastic_thruster>, [[null, <industrialforegoing:plastic>, null],[<industrialforegoing:plastic>, <ironjetpacks:plastic_cell>, <industrialforegoing:plastic>], [null, <slabmachines:furnace_slab>, null]]);
recipes.addShaped(<ironjetpacks:plastic_jetpack>, [[<industrialforegoing:plastic>, null, <industrialforegoing:plastic>],[<industrialforegoing:plastic>, <ironjetpacks:plastic_capacitor>, <industrialforegoing:plastic>], [<ironjetpacks:plastic_thruster>, null, <ironjetpacks:plastic_thruster>]]);
recipes.addShaped(<scannable:scanner>, [[<minestrapp:m_plating:6>, null, <minestrapp:m_plating:6>],[null, <galacticraftcore:basic_item:19>, null], [<galacticraftcore:basic_item:11>, <industrialforegoing:plastic>, <galacticraftcore:basic_item:11>]]);
recipes.addShaped(<galacticraftcore:basic_item:19>, [[null, <minestrapp:m_plating:6>, null],[<galacticraftcore:basic_item:11>, <industrialforegoing:plastic>, <galacticraftcore:basic_item:11>], [<minecraft:redstone>, <industrialforegoing:plastic>, <minecraft:redstone>]]);
recipes.addShaped(<scannable:module_blank>, [[null, <industrialforegoing:plastic>, null],[<industrialforegoing:plastic>, <minestrapp:m_plating:6>, <industrialforegoing:plastic>], [null, <industrialforegoing:plastic>, null]]);
recipes.addShaped(<minecraft:paper> * 6, [[null, null, null],[<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>], [<ore:sugarcane>, <ore:sugarcane>, <ore:sugarcane>]]);
recipes.addShaped(<extraplanets:tools:2>, [[<minecraft:string>, <minecraft:string>, <minecraft:string>],[<minecraft:string>, <exnihilocreatio:item_mesh:1>, <minecraft:string>], [<minecraft:string>, <minecraft:string>, <minecraft:string>]]);
recipes.addShapeless(<galacticraftcore:glowstone_torch>, [<minecraft:torch>]);
recipes.addShapeless(<minecraft:dirt> * 2, [<galacticraftplanets:asteroids_block:2>,<minecraft:cobblestone>]);
recipes.addShapeless(<minecraft:dirt> * 2, [<galacticraftplanets:asteroids_block:1>,<minecraft:cobblestone>]);
recipes.addShapeless(<minecraft:dirt> * 2, [<galacticraftplanets:asteroids_block>,<minecraft:cobblestone>]);
recipes.addShapeless(<scannable:module_ore_rare>, [<scannable:module_blank>,<galacticraftcore:basic_item:13>]);
recipes.addShaped(<powersuits:power_fist>, [[null, <powersuits:powerarmorcomponent>, null],[<powersuits:powerarmorcomponent>, <matteroverdrive:tritanium_ingot>, null], [null, <matteroverdrive:tritanium_ingot>, <galacticraftcore:basic_item:14>]]);
recipes.addShaped(<environmentaltech:structure_frame_1>, [[null, <extraplanets:tier10_items:5>, null],[<environmentaltech:litherite_crystal>, <environmentaltech:interconnect>, <environmentaltech:litherite_crystal>], [null, <minecraft:dye:4>, null]]);
recipes.addShaped(<galacticraftplanets:mars_machine_t2:4>, [[<galacticraftcore:oxygen_tank_heavy_full:2700>.anyDamage(), <galacticraftcore:air_vent>, <galacticraftcore:oxygen_tank_heavy_full:2700>.anyDamage()],[<galacticraftcore:fluid_pipe>, <galacticraftplanets:item_basic_mars:6>, <galacticraftcore:fluid_pipe>], [<galacticraftcore:machine_tiered:4>, <extraplanets:wafer:1>, <galacticraftcore:oxygen_compressor>]]);
recipes.addShaped(<storagenetwork:master>, [[<galacticraftplanets:item_basic_mars:3>, <storagenetwork:kabel>, <galacticraftplanets:item_basic_mars:3>],[<storagenetwork:kabel>, <galacticraftcore:basic_item:14>, <storagenetwork:kabel>], [<galacticraftplanets:item_basic_mars:3>, <storagenetwork:kabel>, <galacticraftplanets:item_basic_mars:3>]]);
recipes.addShaped(<galacticraftcore:machine2>, [[<galacticraftcore:basic_item:9>, <minestrapp:m_plating:6>, <galacticraftcore:basic_item:9>],[<galacticraftcore:aluminum_wire>, <galacticraftcore:machine:12>, <galacticraftcore:aluminum_wire>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<galacticraftcore:machine_tiered:12>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <galacticraftcore:machine_tiered:4>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:13>, <galacticraftcore:basic_item:11>]]);
recipes.addShaped(<galacticraftcore:machine_tiered:4>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <minecraft:furnace>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:11>, <minestrapp:m_plating:6>, <galacticraftcore:basic_item:11>]]);
recipes.addShaped(<mekanism:basicblock2:6>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:13>, <galacticraftcore:basic_item:11>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<mekanism:basicblock2:8> * 2, [[null, <mekanism:basicblock2:7>, null],[<mekanism:basicblock2:7>, <galacticraftcore:basic_item:14>, <mekanism:basicblock2:7>], [null, <mekanism:basicblock2:7>, null]]);
recipes.addShaped(<mekanism:basicblock:15>, [[null, <mekanism:basicblock2>, null],[<mekanism:basicblock2>, <galacticraftcore:basic_item:14>, <mekanism:basicblock2>], [null, <mekanism:basicblock2>, null]]);
recipes.addShaped(<mekanism:basicblock:14>, [[<galacticraftcore:basic_item:14>, <ore:paneGlassColorless>, <galacticraftcore:basic_item:14>],[<mekanism:basicblock2>, <mekanism:machineblock2:11>, <mekanism:basicblock2>], [<mekanism:basicblock2>, <mekanism:basicblock2>, <mekanism:basicblock2>]]);
recipes.addShapeless(<minestrapp:m_leather:13>, [<minecraft:leather>]);
recipes.addShaped(<minestrapp:m_plating:6>, [[null, null, null],[<minecraft:iron_nugget>, <minecraft:iron_ingot>, <minecraft:iron_nugget>], [<minecraft:iron_nugget>, <minecraft:iron_ingot>, <minecraft:iron_nugget>]]);
recipes.addShaped(<minestrapp:iron_dagger>, [[null, null, null],[null, null, <minestrapp:m_plating:6>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<galacticraftcore:machine:12>, [[<minecraft:iron_ingot>, <minestrapp:m_plating:6>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <exnihilocreatio:hammer_wood>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<rftools:matter_transmitter>, [[<rftools:infused_enderpearl>, <rftools:infused_enderpearl>, <rftools:infused_enderpearl>],[<mekanism:reinforcedalloy>, <mekanism:basicblock:8>, <mekanism:reinforcedalloy>], [<extraplanets:tier10_items:5>, <extraplanets:tier10_items:5>, <extraplanets:tier10_items:5>]]);
recipes.addShaped(<rftools:matter_receiver>, [[<extraplanets:tier10_items:5>, <extraplanets:tier10_items:5>, <extraplanets:tier10_items:5>],[<mekanism:reinforcedalloy>, <mekanism:basicblock:8>, <mekanism:reinforcedalloy>], [<moreplanets:dark_energy_pearl>, <moreplanets:dark_energy_pearl>, <moreplanets:dark_energy_pearl>]]);
recipes.addShaped(<rftools:shape_card:2>, [[<mekanism:reinforcedalloy>, <minestrapp:titanium_pickaxe>, <mekanism:reinforcedalloy>],[<minestrapp:m_ingot:6>, <rftools:shape_card>, <minestrapp:m_ingot:6>], [<mekanism:reinforcedalloy>, <minestrapp:titanium_shovel>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<minecraft:diamond_sword>, [[null, <minecraft:diamond>, null],[null, <minecraft:diamond>, null], [null, <exnihilocreatio:item_material:6>, null]]);
recipes.addShaped(<minecraft:diamond_pickaxe>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>],[null, <exnihilocreatio:item_material:6>, null], [null, <exnihilocreatio:item_material:6>, null]]);
recipes.addShaped(<minecraft:diamond_hoe>, [[<minecraft:diamond>, <minecraft:diamond>, null],[null, <exnihilocreatio:item_material:6>, null], [null, <exnihilocreatio:item_material:6>, null]]);
recipes.addShaped(<minecraft:diamond_axe>, [[<minecraft:diamond>, <minecraft:diamond>, null],[<minecraft:diamond>, <exnihilocreatio:item_material:6>, null], [null, <exnihilocreatio:item_material:6>, null]]);
recipes.addShaped(<ultimatecobblegen:dustgenerator>, [[<minecraft:diamond_shovel>, <exnihilocreatio:block_dust>, <minecraft:diamond_shovel>],[<exnihilocreatio:block_dust>, <ultimatecobblegen:cobblegenerator>, <exnihilocreatio:block_dust>], [<minecraft:diamond_shovel>, <exnihilocreatio:block_dust>, <minecraft:diamond_shovel>]]);
recipes.addShapeless(<minecraft:stick>, [<exnihilocreatio:item_material:6>]);
recipes.addShaped(<simplegenerators:culinary_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_guardian>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:reinforcedalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<simplegenerators:ender_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_enderman>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:reinforcedalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<simplegenerators:geothermal_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_blaze>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:reinforcedalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<simplegenerators:fluid_combustion_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_witch>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:reinforcedalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<simplegenerators:combustion_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_creeper>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:reinforcedalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<simplegenerators:soul_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_wither_skeleton>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:reinforcedalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<simplegenerators:nether_simple>, [[<galacticraftcore:basic_item:9>, <deepmoblearning:pristine_matter_wither>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <inventorygenerators:inv_furnace_gen>, <galacticraftcore:basic_item:9>], [<galacticraftcore:basic_item:9>, <mekanism:atomicalloy>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<inventorygenerators:inv_overclocked_gen>, [[<minecraft:dye:4>, <minecraft:dye:4>, <minecraft:dye:4>],[<minecraft:dye:4>, <deepmoblearning:pristine_matter_enderman>, <minecraft:dye:4>], [<mekanism:reinforcedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_culinary_gen>, [[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>],[<minecraft:wheat>, <deepmoblearning:pristine_matter_guardian>, <minecraft:wheat>], [<mekanism:enrichedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_explosive_gen>, [[<minecraft:gunpowder>, <minecraft:gunpowder>, <minecraft:gunpowder>],[<minecraft:gunpowder>, <deepmoblearning:pristine_matter_creeper>, <minecraft:gunpowder>], [<mekanism:enrichedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_potion_gen>, [[<minecraft:spider_eye>, <minecraft:spider_eye>, <minecraft:spider_eye>],[<minecraft:spider_eye>, <deepmoblearning:pristine_matter_spider>, <minecraft:spider_eye>], [<mekanism:enrichedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_pink_gen>, [[<minecraft:dye:9>, <minecraft:dye:9>, <minecraft:dye:9>],[<minecraft:dye:9>, <deepmoblearning:pristine_matter_shulker>, <minecraft:dye:9>], [<mekanism:reinforcedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_pink_gen>, [[<minecraft:shulker_shell>, <minecraft:shulker_shell>, <minecraft:shulker_shell>],[<minecraft:shulker_shell>, <deepmoblearning:pristine_matter_shulker>, <minecraft:shulker_shell>], [<mekanism:reinforcedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_halitosis_gen>, [[<minecraft:skull:1>, <minecraft:skull:1>, <minecraft:skull:1>],[<minecraft:skull:1>, <deepmoblearning:pristine_matter_wither_skeleton>, <minecraft:skull:1>], [<mekanism:reinforcedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_frosty_gen>, [[<minecraft:snowball>, <minecraft:snowball>, <minecraft:snowball>],[<minecraft:snowball>, <deepmoblearning:pristine_matter_witch>, <minecraft:snowball>], [<mekanism:enrichedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_end_gen>, [[<minecraft:ender_eye>, <minecraft:ender_eye>, <minecraft:ender_eye>],[<minecraft:ender_eye>, <deepmoblearning:pristine_matter_dragon>, <minecraft:ender_eye>], [<mekanism:atomicalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:atomicalloy>]]);
recipes.addShaped(<inventorygenerators:inv_death_gen>, [[<minecraft:bone>, <minecraft:bone>, <minecraft:bone>],[<minecraft:bone>, <deepmoblearning:pristine_matter_skeleton>, <minecraft:bone>], [<mekanism:enrichedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_slimey_gen>, [[<ore:slimeball>, <ore:slimeball>, <ore:slimeball>],[<ore:slimeball>, <deepmoblearning:pristine_matter_slime>, <ore:slimeball>], [<mekanism:enrichedalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<inventorygenerators:inv_nether_star_gen>, [[<minecraft:nether_star>, <minecraft:nether_star>, <minecraft:nether_star>],[<minecraft:nether_star>, <deepmoblearning:pristine_matter_wither>, <minecraft:nether_star>], [<mekanism:atomicalloy>, <inventorygenerators:inv_furnace_gen>, <mekanism:atomicalloy>]]);
recipes.addShaped(<valkyrielib:modifier_component>, [[<extraplanets:tier4_items:4>, <mekanism:enrichedalloy>, <extraplanets:tier4_items:4>],[<mekanism:enrichedalloy>, <ore:compressedSteel>, <mekanism:enrichedalloy>], [<extraplanets:tier4_items:4>, <mekanism:enrichedalloy>, <extraplanets:tier4_items:4>]]);
recipes.addShaped(<powersuits:powerarmorcomponent:4>, [[null, <powersuits:powerarmorcomponent:12>, <powersuits:powerarmorcomponent:1>],[<extraplanets:tier11_items>, <minecraft:glowstone_dust>, null], [<powersuits:powerarmorcomponent>, <powersuits:powerarmorcomponent:12>, <powersuits:powerarmorcomponent:1>]]);
recipes.addShaped(<powersuits:tinkertable>, [[<extraplanets:tier4_items:5>, <extraplanets:tier4_items:6>, <extraplanets:tier4_items:5>],[<extraplanets:tier4_items:6>, <minecraft:diamond>, <extraplanets:tier4_items:6>], [<extraplanets:tier4_items:5>, <extraplanets:tier4_items:6>, <extraplanets:tier4_items:5>]]);
recipes.addShaped(<extraplanets:tier1_space_suit_jetpack_chest:100>, [[<galacticraftcore:battery:100>, <galacticraftcore:battery:100>, <galacticraftcore:battery:100>],[<extraplanets:tier10_items>, <extraplanets:tier4_space_suit_chest:100>, <extraplanets:tier10_items>], [<galacticraftcore:battery:100>, <galacticraftcore:battery:100>, <galacticraftcore:battery:100>]]);
recipes.addShaped(<powersuits:powerarmor_feet>, [[null, null, null],[<powersuits:powerarmorcomponent>, null, <powersuits:powerarmorcomponent>], [<extraplanets:tier5_items:5>, null, <extraplanets:tier5_items:5>]]);
recipes.addShaped(<powersuits:powerarmor_legs>, [[<extraplanets:tier5_items:5>, <extraplanets:tier5_items:5>, <extraplanets:tier5_items:5>],[<powersuits:powerarmorcomponent>, null, <powersuits:powerarmorcomponent>], [<extraplanets:tier5_items:5>, null, <extraplanets:tier5_items:5>]]);
recipes.addShaped(<powersuits:powerarmor_torso>, [[<extraplanets:tier5_items:5>, null, <extraplanets:tier5_items:5>],[<powersuits:powerarmorcomponent>, <extraplanets:tier5_items:5>, <powersuits:powerarmorcomponent>], [<extraplanets:tier5_items:5>, <extraplanets:tier5_items:5>, <extraplanets:tier5_items:5>]]);
recipes.addShaped(<powersuits:powerarmor_head>, [[null, null, null],[<extraplanets:tier5_items:5>, <extraplanets:tier5_items:5>, <extraplanets:tier5_items:5>], [<powersuits:powerarmorcomponent>, null, <powersuits:powerarmorcomponent>]]);
recipes.addShaped(<mekanismgenerators:generator:6>, [[null, <minestrapp:m_ingot:5>, null],[<minestrapp:m_ingot:5>, <mekanism:enrichedalloy>, <minestrapp:m_ingot:5>], [<mekanism:energytablet>, <mekanism:controlcircuit>, <mekanism:energytablet>]]);
recipes.addShaped(<minecraft:hopper>, [[<galacticraftcore:basic_item:9>, null, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <minecraft:chest>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<deepmoblearning:glitch_infused_boots>, [[null, null, null],[<deepmoblearning:glitch_infused_ingot>, null, <deepmoblearning:glitch_infused_ingot>], [<deepmoblearning:glitch_infused_ingot>, <extraplanets:tier11_items:4>, <deepmoblearning:glitch_infused_ingot>]]);
recipes.addShaped(<deepmoblearning:glitch_infused_leggings>, [[<deepmoblearning:glitch_infused_ingot>, <extraplanets:tier11_items:4>, <deepmoblearning:glitch_infused_ingot>],[<deepmoblearning:glitch_infused_ingot>, null, <deepmoblearning:glitch_infused_ingot>], [<deepmoblearning:glitch_infused_ingot>, null, <deepmoblearning:glitch_infused_ingot>]]);
recipes.addShaped(<deepmoblearning:glitch_infused_helmet>, [[<deepmoblearning:glitch_infused_ingot>, <deepmoblearning:glitch_infused_ingot>, <deepmoblearning:glitch_infused_ingot>],[<deepmoblearning:glitch_infused_ingot>, <extraplanets:tier11_items:4>, <deepmoblearning:glitch_infused_ingot>], [null, null, null]]);
recipes.addShaped(<deepmoblearning:glitch_infused_chestplate>, [[<deepmoblearning:glitch_infused_ingot>, null, <deepmoblearning:glitch_infused_ingot>],[<deepmoblearning:glitch_infused_ingot>, <extraplanets:tier11_items>, <deepmoblearning:glitch_infused_ingot>], [<deepmoblearning:glitch_infused_ingot>, <deepmoblearning:glitch_infused_ingot>, <deepmoblearning:glitch_infused_ingot>]]);
recipes.addShaped(<mekanism:configurator>, [[null, null, <minecraft:dye:4>],[null, <mekanism:enrichedalloy>, null], [<minecraft:stick>, null, null]]);
recipes.addShapeless(<minecraft:clay_ball> * 4, [<minecraft:clay>]);
recipes.addShapeless(<minecraft:quartz> * 4, [<ore:blockQuartz>]);
recipes.addShapeless(<minecraft:glowstone_dust> * 4, [<minecraft:glowstone>]);
recipes.addShaped(<minecraft:glowstone_dust> * 4, [[null, null, null],[null, <minecraft:glowstone>, null], [null, null, null]]);
recipes.addShaped(<minecraft:clay_ball> * 4, [[null, null, null],[null, <minecraft:clay>, null], [null, null, null]]);
recipes.addShaped(<minecraft:quartz> * 4, [[null, null, null],[null, <ore:blockQuartz>, null], [null, null, null]]);
recipes.addShaped(<minecraft:furnace>, [[null, null, null],[null, <slabmachines:furnace_slab>, null], [null, <slabmachines:furnace_slab>, null]]);
recipes.addShaped(<mekanism:jetpack>, [[<lcrdrfs:jet_control_unit>, <mekanism:controlcircuit:1>, <lcrdrfs:jet_control_unit>],[<lcrdrfs:jet_thruster>, <mekanism:gastank>.withTag({tier: 0, mekData: {}}).onlyWithTag({tier: 0, mekData: {}}), <lcrdrfs:jet_thruster>], [<extraplanets:tier6_items:5>, <lcrdrfs:jet_control_unit>, <extraplanets:tier6_items:5>]]);
recipes.addShaped(<lcrdrfs:jetpack>, [[null, <lcrdrfs:jet_control_unit>, null],[<lcrdrfs:jet_control_unit>, <ironjetpacks:platinum_jetpack>, <lcrdrfs:jet_control_unit>], [<lcrdrfs:jet_thruster>, <extraplanets:tier11_items:1>, <lcrdrfs:jet_thruster>]]);
recipes.addShaped(<slabmachines:furnace_slab>, [[<minecraft:stone_slab:3>, <minecraft:stone_slab:3>, <minecraft:stone_slab:3>],[<minecraft:stone_slab:3>, null, <minecraft:stone_slab:3>], [<minecraft:stone_slab:3>, <minecraft:stone_slab:3>, <minecraft:stone_slab:3>]]);
recipes.addShaped(<slabmachines:furnace_slab> * 2, [[null, null, null],[null, <minecraft:furnace>, null], [null, null, null]]);
recipes.addShaped(<mekanism:machineblock:11>, [[<extraplanets:tier4_items:4>, <mekanism:controlcircuit>, <extraplanets:tier4_items:4>],[<mekanism:controlcircuit>, <mekanism:teleportationcore>, <mekanism:controlcircuit>], [<extraplanets:tier4_items:4>, <mekanism:controlcircuit>, <extraplanets:tier4_items:4>]]);
recipes.addShaped(<mekanism:basicblock:8>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:11>, <mekanism:ingot:1>, <galacticraftcore:basic_item:11>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<mekanism:basicblock2> * 4, [[null, <galacticraftcore:basic_item:9>, null],[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:6>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<mekanism:basicblock2:7> * 4, [[null, <galacticraftcore:basic_item:9>, null],[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<rftools:machine_frame>, [[<matteroverdrive:tritanium_ingot>, <galacticraftcore:basic_item:9>, <matteroverdrive:tritanium_ingot>],[<galacticraftcore:basic_item:11>, null, <galacticraftcore:basic_item:11>], [<matteroverdrive:tritanium_ingot>, <galacticraftcore:basic_item:9>, <matteroverdrive:tritanium_ingot>]]);
recipes.addShaped(<galacticraftcore:refinery>, [[<galacticraftplanets:item_basic_mars:6>, <galacticraftcore:machine_tiered:4>, <galacticraftplanets:item_basic_mars:6>],[<moreplanets:diona_item:5>, <industrialforegoing:fluid_pump>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <extraplanets:tier11_items:4>, <moreplanets:diona_item:5>]]);
recipes.addShapeless(<minecraft:flint>, [<minecraft:gravel>,<minecraft:gravel>,<minecraft:gravel>]);
recipes.addShaped(<extraplanets:tier1_radiation_layer>, [[null, <galacticraftcore:basic_item:11>, null],[<galacticraftcore:basic_item:8>, <minecraft:paper>, <galacticraftcore:basic_item:8>], [null, <galacticraftcore:basic_item:11>, null]]);
recipes.addShaped(<galacticraftplanets:item_basic_mars:6>, [[<rftools:infused_enderpearl>, <galacticraftcore:air_fan>, <rftools:infused_enderpearl>],[<minecraft:slime_ball>, <galacticraftcore:basic_item:14>, <minecraft:slime_ball>], [<rftools:infused_diamond>, <galacticraftcore:air_fan>, <rftools:infused_diamond>]]);
recipes.addShapeless(<galacticraftplanets:carbon_fragments> * 16, [<minecraft:coal:1>,<minecraft:coal:1>,<minecraft:coal:1>,<minecraft:coal:1>]);
recipes.addShapeless(<galacticraftplanets:carbon_fragments> * 32, [<minecraft:coal>,<minecraft:coal>,<minecraft:coal>,<minecraft:coal>]);
recipes.addShaped(<deepmoblearning:trial_keystone>, [[<minecraft:diamond>, <deepmoblearning:trial_key>, <minecraft:diamond>],[<minestrapp:decor_stone:7>, <deepmoblearning:machine_casing>, <minestrapp:decor_stone:7>], [<minestrapp:decor_stone:7>, <minestrapp:decor_stone:7>, <minestrapp:decor_stone:7>]]);
recipes.addShaped(<ultimatecobblegen:grassgenerator>, [[<minecraft:golden_shovel>, <minecraft:golden_shovel>, <minecraft:golden_shovel>],[<minecraft:lava_bucket>, <minecraft:grass>, <minecraft:water_bucket>], [<minecraft:golden_shovel>, <deepmoblearning:pristine_matter_zombie>, <minecraft:golden_shovel>]]);
recipes.addShaped(<industrialforegoing:material_stonework_factory>, [[<industrialforegoing:plastic>, <minecraft:crafting_table>, <industrialforegoing:plastic>],[<matteroverdrive:tritanium_pickaxe>, <mekanism:basicblock:8>, <minecraft:furnace>], [<minecraft:lava_bucket>, <industrialforegoing:pink_slime>, <minecraft:water_bucket>]]);
recipes.addShaped(<appliedenergistics2:wireless_terminal>, [[null, <appliedenergistics2:material:41>, null],[null, <appliedenergistics2:part:380>, null], [<extraplanets:tier8_items:6>, <appliedenergistics2:dense_energy_cell>.anyDamage(), <extraplanets:tier8_items:6>]]);
recipes.addShaped(<wct:wct>, [[<appliedenergistics2:wireless_terminal>.anyDamage(), <appliedenergistics2:material:9>, null],[<appliedenergistics2:part:360>, <moreplanets:dark_energy_pearl>, null], [null, null, null]]);
recipes.addShaped(<moreplanets:black_hole_storage>, [[<galacticraftcore:steel_pole>, <moreplanets:diona_item:7>, <galacticraftcore:steel_pole>],[<moreplanets:diona_item:6>, <moreplanets:diona_item:5>, <moreplanets:diona_item:6>], [<moreplanets:diona_item:6>, <moreplanets:dark_energy_pearl>, <moreplanets:diona_item:6>]]);
recipes.addShaped(<moreplanets:diona_item:7>, [[<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>],[<moreplanets:diona_item:5>, <moreplanets:dark_energy_pearl>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>]]);
recipes.addShaped(<moreplanets:dark_energy_pearl>, [[<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>],[<moreplanets:diona_item:5>, <minecraft:ender_pearl>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>]]);
recipes.addShaped(<moreplanets:diona_item:6>, [[<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>],[<moreplanets:diona_item:5>, <minecraft:iron_ingot>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>]]);
recipes.addShaped(<ultimatecobblegen:fungusgenerator>, [[<minecraft:diamond_shovel>, <minecraft:diamond_shovel>, <minecraft:diamond_shovel>],[<minecraft:lava_bucket>, <minecraft:mycelium>, <minecraft:water_bucket>], [<minecraft:diamond_shovel>, <extraplanets:tier6_items:4>, <minecraft:diamond_shovel>]]);
recipes.addShaped(<ultimatecobblegen:obsidiangenerator>, [[<minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>],[<minecraft:lava_bucket>, <minecraft:obsidian>, <minecraft:water_bucket>], [<minecraft:diamond_pickaxe>, <extraplanets:ingot_mercury>, <minecraft:diamond_pickaxe>]]);
recipes.addShaped(<ultimatecobblegen:snowgenerator>, [[<minecraft:diamond_shovel>, <minecraft:diamond_shovel>, <minecraft:diamond_shovel>],[<minecraft:water_bucket>, <minecraft:snowball>, <minecraft:water_bucket>], [<minecraft:diamond_shovel>, <extraplanets:tier5_items:4>, <minecraft:diamond_shovel>]]);
recipes.addShaped(<ultimatecobblegen:icegenerator>, [[<minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>],[<minecraft:water_bucket>, <minecraft:snowball>, <minecraft:water_bucket>], [<minecraft:diamond_pickaxe>, <extraplanets:tier5_items:4>, <minecraft:diamond_pickaxe>]]);
recipes.addShaped(<ultimatecobblegen:gravelgenerator>, [[<minecraft:golden_pickaxe>, <minecraft:golden_pickaxe>, <minecraft:golden_pickaxe>],[<minecraft:lava_bucket>, <minecraft:gravel>, <minecraft:water_bucket>], [<minecraft:golden_pickaxe>, <deepmoblearning:pristine_matter_skeleton>, <minecraft:golden_pickaxe>]]);
recipes.addShaped(<matteroverdrive:replicator>, [[<matteroverdrive:pattern_drive>, <matteroverdrive:isolinear_circuit:2>, <matteroverdrive:network_flash_drive>],[<extraplanets:tier11_items>, <matteroverdrive:h_compensator>, <extraplanets:tier11_items>], [<matteroverdrive:integration_matrix>, <matteroverdrive:tritanium_plate>, <matteroverdrive:me_conversion_matrix>]]);
recipes.addShaped(<matteroverdrive:decomposer>, [[<matteroverdrive:tritanium_plate>, <matteroverdrive:isolinear_circuit:2>, <matteroverdrive:tritanium_plate>],[<minecraft:sticky_piston>, <extraplanets:tier11_items>, <minecraft:sticky_piston>], [<matteroverdrive:integration_matrix>, <matteroverdrive:tritanium_plate>, <matteroverdrive:me_conversion_matrix>]]);
recipes.addShaped(<matteroverdrive:matter_analyzer>, [[<extraplanets:tier11_items>, <matteroverdrive:isolinear_circuit:2>, <extraplanets:tier11_items>],[<matteroverdrive:pattern_drive>, <matteroverdrive:me_conversion_matrix>, <matteroverdrive:network_flash_drive>], [<extraplanets:tier11_items>, <matteroverdrive:integration_matrix>, <extraplanets:tier11_items>]]);
recipes.addShaped(<appliedenergistics2:material:38>, [[<extraplanets:tier9_items:5>, <appliedenergistics2:material:23>, <extraplanets:tier9_items:5>],[<appliedenergistics2:material:37>, <appliedenergistics2:quartz_glass>, <appliedenergistics2:material:37>], [<extraplanets:tier9_items:5>, <appliedenergistics2:material:37>, <extraplanets:tier9_items:5>]]);
recipes.addShaped(<appliedenergistics2:material:37>, [[<extraplanets:tier7_items:5>, <appliedenergistics2:material:23>, <extraplanets:tier7_items:5>],[<appliedenergistics2:material:36>, <appliedenergistics2:quartz_glass>, <appliedenergistics2:material:36>], [<extraplanets:tier7_items:5>, <appliedenergistics2:material:36>, <extraplanets:tier7_items:5>]]);
recipes.addShaped(<appliedenergistics2:material:36>, [[<extraplanets:tier6_items:5>, <appliedenergistics2:material:23>, <extraplanets:tier6_items:5>],[<appliedenergistics2:material:35>, <appliedenergistics2:quartz_glass>, <appliedenergistics2:material:35>], [<extraplanets:tier6_items:5>, <appliedenergistics2:material:35>, <extraplanets:tier6_items:5>]]);
recipes.addShaped(<appliedenergistics2:material:35>, [[<extraplanets:tier5_items:5>, <ore:crystalPureCertusQuartz>, <extraplanets:tier5_items:5>],[<ore:crystalPureCertusQuartz>, <appliedenergistics2:material:22>, <ore:crystalPureCertusQuartz>], [<extraplanets:tier5_items:5>, <ore:crystalPureCertusQuartz>, <extraplanets:tier5_items:5>]]);
recipes.addShaped(<appliedenergistics2:controller>, [[<appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material:12>, <appliedenergistics2:smooth_sky_stone_block>],[<extraplanets:ingot_uranium>, <appliedenergistics2:material:24>, <extraplanets:tier5_items:5>], [<appliedenergistics2:smooth_sky_stone_block>, <extraplanets:tier5_items:8>, <appliedenergistics2:smooth_sky_stone_block>]]);
recipes.addShaped(<minecraft:slime_ball>, [[<minecraft:dye:2>, <minecraft:sugar>, <minecraft:dye:2>],[<minecraft:sugar>, <appliedenergistics2:material:46>, <minecraft:sugar>], [<minecraft:dye:2>, <minecraft:sugar>, <minecraft:dye:2>]]);
recipes.addShapeless(<industrialforegoing:pink_slime>, [<ore:slimeball>,<industrialforegoing:laser_lens_inverted:6>]);
recipes.addShaped(<storagenetwork:kabel> * 4, [[null, null, null],[null, <appliedenergistics2:part:140>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<minestrapp:m_tech_component>, [[null, null, <minestrapp:m_gem:6>],[null, <ore:stickWood>, null], [<minestrapp:m_gem:6>, null, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_boots:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_boots>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_legings:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_legings>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_chest:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_chest>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_helmet:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_helmet>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShapeless(<minecraft:cobblestone> * 2, [<galacticraftplanets:asteroids_block:*>,<galacticraftplanets:asteroids_block:*>]);
//recipes.addShaped(<storagenetwork:kabel> * 6, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:9>, null, <enderio:item_alloy_ingot:9>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
//File End
