//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<matteroverdrive:omni_tool>);
recipes.remove(<matteroverdrive:plasma_shotgun>);
recipes.remove(<matteroverdrive:phaser>);
recipes.remove(<matteroverdrive:ion_sniper>);
recipes.remove(<matteroverdrive:phaser_rifle>);
recipes.remove(<minecraft:hopper>);
recipes.remove(<galacticraftcore:fluid_tank>);
recipes.remove(<mekanism:jetpack>);
recipes.remove(<lcrdrfs:jetpack>);
recipes.remove(<exnihilocreatio:block_crucible>);
recipes.removeShaped(<slabmachines:furnace_slab>);
furnace.remove(<exnihilocreatio:block_crucible:0>);
recipes.remove(<minecraft:dirt>);
recipes.remove(<galacticraftcore:rocket_workbench>);
recipes.remove(<exnihilocreatio:block_crucible:1>);
recipes.remove(<mekanism:machineblock:11>);
recipes.remove(<mekanism:basicblock:8>);
recipes.remove(<mekanism:machineblock:4>);
recipes.remove(<mekanism:basicblock2> * 4);
recipes.remove(<mekanism:basicblock2:7> * 4);
recipes.remove(<rftools:machine_frame>);
recipes.remove(<rftools:matter_receiver>);
recipes.remove(<rftools:matter_transmitter>);
recipes.remove(<rftools:matter_transmitter>);
recipes.remove(<galacticraftplanets:item_basic_mars:6>);
recipes.remove(<galacticraftplanets:carbon_fragments>);
recipes.remove(<deepmoblearning:trial_keystone>);
recipes.remove(<simplegenerators:nether_simple>);
recipes.remove(<industrialforegoing:material_stonework_factory>);
recipes.remove(<ultimatecobblegen:dustgenerator>);
recipes.remove(<appliedenergistics2:wireless_terminal>);
recipes.remove(<wct:wct>);
recipes.remove(<ultimatecobblegen:fungusgenerator>);
recipes.remove(<ultimatecobblegen:obsidiangenerator>);
recipes.remove(<ultimatecobblegen:snowgenerator>);
recipes.remove(<ultimatecobblegen:icegenerator>);
recipes.remove(<ultimatecobblegen:grassgenerator>);
recipes.remove(<ultimatecobblegen:gravelgenerator>);
recipes.remove(<matteroverdrive:replicator>);
recipes.remove(<matteroverdrive:decomposer>);
recipes.remove(<matteroverdrive:matter_analyzer>);
recipes.remove(<storagenetwork:master>);
recipes.remove(<appliedenergistics2:material:38>);
recipes.remove(<appliedenergistics2:material:37>);
recipes.remove(<appliedenergistics2:material:36>);
recipes.remove(<appliedenergistics2:material:35>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<inventorygenerators:inv_end_gen>);
recipes.remove(<inventorygenerators:inv_halitosis_gen>);
recipes.remove(<inventorygenerators:inv_nether_star_gen>);
recipes.remove(<inventorygenerators:inv_furnace_gen>);
recipes.remove(<minecraft:furnace>);
recipes.remove(<galacticraftcore:refinery>);
recipes.remove(<extraplanets:tier1_space_suit_boots>);
recipes.remove(<extraplanets:tier1_space_suit_legings>);
recipes.remove(<extraplanets:tier1_space_suit_chest>);
recipes.remove(<extraplanets:tier1_space_suit_helmet>);
recipes.remove(<extraplanets:tier1_radiation_layer>);
recipes.remove(<minestrapp:m_tech_component> * 8);
//recipes.remove(<galacticraftcore:refinery>);
//recipes.remove(<teslathingies:crop_cloner>);
recipes.remove(<extraplanets:tier1_space_suit_boots:100>);
recipes.remove(<extraplanets:tier1_space_suit_legings:100>);
recipes.remove(<extraplanets:tier1_space_suit_chest:100>);
recipes.remove(<extraplanets:tier1_space_suit_helmet:100>);
recipes.remove(<galacticraftcore:machine:12>);
recipes.remove(<galacticraftcore:basic_item:19>);
recipes.remove(<scannable:scanner>);
recipes.remove(<extraplanets:anti_radiation>);
recipes.remove(<exnihilocreatio:block_end_cake>);
recipes.remove(<storagenetwork:kabel>);
//Don't touch me!
//#Add
recipes.addShaped(<exnihilocreatio:block_crucible:1>, [[<exnihilocreatio:item_material:1>, null, <exnihilocreatio:item_material:1>],[<exnihilocreatio:item_material:1>, <exnihilocreatio:item_doll>, <exnihilocreatio:item_material:1>], [<exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>]]);
recipes.addShaped(<minecraft:hopper>, [[<galacticraftcore:basic_item:9>, null, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <minestrapp:pipe>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<minecraft:furnace>, [[null, null, null],[null, <slabmachines:furnace_slab>, null], [null, <slabmachines:furnace_slab>, null]]);
recipes.addShaped(<mekanism:jetpack>, [[<lcrdrfs:jet_control_unit>, <mekanism:controlcircuit:1>, <lcrdrfs:jet_control_unit>],[<lcrdrfs:jet_thruster>, <mekanism:gastank>.withTag({tier: 0, mekData: {}}).onlyWithTag({tier: 0, mekData: {}}), <lcrdrfs:jet_thruster>], [<extraplanets:tier6_items:5>, <lcrdrfs:jet_control_unit>, <extraplanets:tier6_items:5>]]);
recipes.addShaped(<lcrdrfs:jetpack>, [[null, <lcrdrfs:jet_control_unit>, null],[<lcrdrfs:jet_control_unit>, <ironjetpacks:platinum_jetpack>, <lcrdrfs:jet_control_unit>], [<lcrdrfs:jet_thruster>, <extraplanets:tier11_items:1>, <lcrdrfs:jet_thruster>]]);
recipes.addShaped(<slabmachines:furnace_slab>, [[<minecraft:stone_slab:3>, <minecraft:stone_slab:3>, <minecraft:stone_slab:3>],[<minecraft:stone_slab:3>, null, <minecraft:stone_slab:3>], [<minecraft:stone_slab:3>, <minecraft:stone_slab:3>, <minecraft:stone_slab:3>]]);
recipes.addShaped(<slabmachines:furnace_slab> * 2, [[null, null, null],[null, <minecraft:furnace>, null], [null, null, null]]);
recipes.addShaped(<mekanism:machineblock:11>, [[<extraplanets:tier4_items:4>, <mekanism:controlcircuit>, <extraplanets:tier4_items:4>],[<mekanism:controlcircuit>, <mekanism:teleportationcore>, <mekanism:controlcircuit>], [<extraplanets:tier4_items:4>, <mekanism:controlcircuit>, <extraplanets:tier4_items:4>]]);
recipes.addShaped(<mekanism:basicblock:8>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:11>, <mekanism:ingot:1>, <galacticraftcore:basic_item:11>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<mekanism:machineblock:4>, [[<extraplanets:tier7_items:5>, <mekanism:atomicalloy>, <extraplanets:tier5_items:7>],[<mekanism:machineblock:15>, <mekanism:robit>, <mekanism:machineblock:15>], [<matteroverdrive:tritanium_ingot>, <mekanism:teleportationcore>, <extraplanets:tier4_items:5>]]);
recipes.addShaped(<mekanism:basicblock2> * 4, [[null, <galacticraftcore:basic_item:9>, null],[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:6>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<mekanism:basicblock2:7> * 4, [[null, <galacticraftcore:basic_item:9>, null],[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<rftools:machine_frame>, [[<matteroverdrive:tritanium_ingot>, <galacticraftcore:basic_item:9>, <matteroverdrive:tritanium_ingot>],[<galacticraftcore:basic_item:11>, null, <galacticraftcore:basic_item:11>], [<matteroverdrive:tritanium_ingot>, <galacticraftcore:basic_item:9>, <matteroverdrive:tritanium_ingot>]]);
recipes.addShaped(<rftools:matter_receiver>, [[<extraplanets:tier4_items:5>, <extraplanets:tier4_items:5>, <extraplanets:tier4_items:5>],[<deepmoblearning:soot_covered_redstone>, <rftools:machine_frame>, <deepmoblearning:soot_covered_redstone>], [<rftools:infused_enderpearl>, <rftools:infused_enderpearl>, <rftools:infused_enderpearl>]]);
recipes.addShaped(<rftools:matter_transmitter>, [[<rftools:infused_enderpearl>, <rftools:infused_enderpearl>, <rftools:infused_enderpearl>],[<deepmoblearning:soot_covered_redstone>, <rftools:machine_frame>, <deepmoblearning:soot_covered_redstone>], [<extraplanets:tier4_items:5>, <extraplanets:tier4_items:5>, <extraplanets:tier4_items:5>]]);
recipes.addShaped(<storagenetwork:master>, [[<minestrapp:decor_stone:6>, <storagenetwork:kabel>, <minestrapp:decor_stone:6>],[<storagenetwork:kabel>, <minestrapp:m_ingot:4>, <storagenetwork:kabel>], [<minestrapp:decor_stone:6>, <storagenetwork:kabel>, <minestrapp:decor_stone:6>]]);
recipes.addShaped(<galacticraftcore:refinery>, [[<galacticraftplanets:item_basic_mars:6>, <galacticraftcore:machine_tiered:4>, <galacticraftplanets:item_basic_mars:6>],[<moreplanets:diona_item:5>, <industrialforegoing:fluid_pump>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <extraplanets:tier11_items:4>, <moreplanets:diona_item:5>]]);
recipes.addShapeless(<minecraft:flint>, [<minecraft:gravel>,<minecraft:gravel>,<minecraft:gravel>]);
recipes.addShaped(<extraplanets:tier1_radiation_layer>, [[null, <galacticraftcore:basic_item:11>, null],[<galacticraftcore:basic_item:8>, <minecraft:paper>, <galacticraftcore:basic_item:8>], [null, <galacticraftcore:basic_item:11>, null]]);
recipes.addShaped(<galacticraftplanets:item_basic_mars:6>, [[<rftools:infused_enderpearl>, <galacticraftcore:air_fan>, <rftools:infused_enderpearl>],[<minecraft:slime_ball>, <galacticraftcore:basic_item:14>, <minecraft:slime_ball>], [<rftools:infused_diamond>, <galacticraftcore:air_fan>, <rftools:infused_diamond>]]);
recipes.addShapeless(<galacticraftplanets:carbon_fragments> * 16, [<minecraft:coal:1>,<minecraft:coal:1>,<minecraft:coal:1>,<minecraft:coal:1>]);
recipes.addShapeless(<galacticraftplanets:carbon_fragments> * 32, [<minecraft:coal>,<minecraft:coal>,<minecraft:coal>,<minecraft:coal>]);
recipes.addShaped(<deepmoblearning:trial_keystone>, [[<minecraft:diamond>, <deepmoblearning:trial_key>, <minecraft:diamond>],[<minestrapp:decor_stone:7>, <deepmoblearning:machine_casing>, <minestrapp:decor_stone:7>], [<minestrapp:decor_stone:7>, <minestrapp:decor_stone:7>, <minestrapp:decor_stone:7>]]);
recipes.addShaped(<simplegenerators:nether_simple>, [[<excompressum:compressed_block:8>, <deepmoblearning:pristine_matter_wither_skeleton>, <excompressum:compressed_block:8>],[<deepmoblearning:pristine_matter_wither_skeleton>, <minecraft:furnace>, <deepmoblearning:pristine_matter_wither_skeleton>], [<excompressum:compressed_block:8>, <ore:blockRedstone>, <excompressum:compressed_block:8>]]);
recipes.addShaped(<ultimatecobblegen:grassgenerator>, [[<minecraft:golden_shovel>, <minecraft:golden_shovel>, <minecraft:golden_shovel>],[<minecraft:lava_bucket>, <minecraft:grass>, <minecraft:water_bucket>], [<minecraft:golden_shovel>, <deepmoblearning:pristine_matter_zombie>, <minecraft:golden_shovel>]]);
recipes.addShaped(<industrialforegoing:material_stonework_factory>, [[<industrialforegoing:plastic>, <minecraft:crafting_table>, <industrialforegoing:plastic>],[<matteroverdrive:tritanium_pickaxe>, <mekanism:basicblock:8>, <minecraft:furnace>], [<minecraft:lava_bucket>, <industrialforegoing:pink_slime>, <minecraft:water_bucket>]]);
recipes.addShaped(<ultimatecobblegen:dustgenerator>, [[<minecraft:diamond_shovel>.anyDamage(), <minecraft:diamond_shovel>, <minecraft:diamond_shovel>],[<minecraft:lava_bucket>, <exnihilocreatio:block_dust>, <minecraft:water_bucket>], [<minecraft:diamond_shovel>, <extraplanets:tier5_items:5>.anyDamage(), <minecraft:diamond_shovel>]]);
recipes.addShaped(<appliedenergistics2:wireless_terminal>, [[null, <appliedenergistics2:material:41>, null],[null, <appliedenergistics2:part:380>, null], [<extraplanets:tier8_items:6>, <appliedenergistics2:dense_energy_cell>.anyDamage(), <extraplanets:tier8_items:6>]]);
recipes.addShaped(<wct:wct>, [[<appliedenergistics2:wireless_terminal>.anyDamage(), <appliedenergistics2:material:9>, null],[<appliedenergistics2:part:360>, <moreplanets:dark_energy_pearl>, null], [null, null, null]]);
recipes.addShaped(<moreplanets:black_hole_storage>, [[<galacticraftcore:steel_pole>, <moreplanets:diona_item:7>, <galacticraftcore:steel_pole>],[<moreplanets:diona_item:6>, <moreplanets:diona_item:5>, <moreplanets:diona_item:6>], [<moreplanets:diona_item:6>, <moreplanets:dark_energy_pearl>, <moreplanets:diona_item:6>]]);
recipes.addShaped(<moreplanets:diona_item:7>, [[<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>],[<moreplanets:diona_item:5>, <moreplanets:dark_energy_pearl>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>]]);
recipes.addShaped(<moreplanets:dark_energy_pearl>, [[<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>],[<moreplanets:diona_item:5>, <minecraft:ender_pearl>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>]]);
recipes.addShaped(<moreplanets:diona_item:6>, [[<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>],[<moreplanets:diona_item:5>, <minecraft:iron_ingot>, <moreplanets:diona_item:5>], [<moreplanets:diona_item:5>, <moreplanets:diona_item:5>, <moreplanets:diona_item:5>]]);
recipes.addShaped(<ultimatecobblegen:fungusgenerator>, [[<minecraft:diamond_shovel>, <minecraft:diamond_shovel>, <minecraft:diamond_shovel>],[<minecraft:lava_bucket>, <minecraft:mycelium>, <minecraft:water_bucket>], [<minecraft:diamond_shovel>, <extraplanets:tier6_items:4>, <minecraft:diamond_shovel>]]);
recipes.addShaped(<ultimatecobblegen:obsidiangenerator>, [[<minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>],[<minecraft:lava_bucket>, <minecraft:obsidian>, <minecraft:water_bucket>], [<minecraft:diamond_pickaxe>, <extraplanets:ingot_mercury>, <minecraft:diamond_pickaxe>]]);
recipes.addShaped(<ultimatecobblegen:snowgenerator>, [[<minecraft:diamond_shovel>, <minecraft:diamond_shovel>, <minecraft:diamond_shovel>],[<minecraft:water_bucket>, <minecraft:snowball>, <minecraft:water_bucket>], [<minecraft:diamond_shovel>, <extraplanets:tier5_items:4>, <minecraft:diamond_shovel>]]);
recipes.addShaped(<ultimatecobblegen:icegenerator>, [[<minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>, <minecraft:diamond_pickaxe>],[<minecraft:water_bucket>, <minecraft:snowball>, <minecraft:water_bucket>], [<minecraft:diamond_pickaxe>, <extraplanets:tier5_items:4>, <minecraft:diamond_pickaxe>]]);
recipes.addShaped(<ultimatecobblegen:gravelgenerator>, [[<minecraft:golden_pickaxe>, <minecraft:golden_pickaxe>, <minecraft:golden_pickaxe>],[<minecraft:lava_bucket>, <minecraft:gravel>, <minecraft:water_bucket>], [<minecraft:golden_pickaxe>, <deepmoblearning:pristine_matter_skeleton>, <minecraft:golden_pickaxe>]]);
recipes.addShaped(<matteroverdrive:replicator>, [[<matteroverdrive:pattern_drive>, <matteroverdrive:isolinear_circuit:2>, <matteroverdrive:network_flash_drive>],[<extraplanets:tier11_items>, <matteroverdrive:h_compensator>, <extraplanets:tier11_items>], [<matteroverdrive:integration_matrix>, <matteroverdrive:tritanium_plate>, <matteroverdrive:me_conversion_matrix>]]);
recipes.addShaped(<matteroverdrive:decomposer>, [[<matteroverdrive:tritanium_plate>, <matteroverdrive:isolinear_circuit:2>, <matteroverdrive:tritanium_plate>],[<minecraft:sticky_piston>, <extraplanets:tier11_items>, <minecraft:sticky_piston>], [<matteroverdrive:integration_matrix>, <matteroverdrive:tritanium_plate>, <matteroverdrive:me_conversion_matrix>]]);
recipes.addShaped(<matteroverdrive:matter_analyzer>, [[<extraplanets:tier11_items>, <matteroverdrive:isolinear_circuit:2>, <extraplanets:tier11_items>],[<matteroverdrive:pattern_drive>, <matteroverdrive:me_conversion_matrix>, <matteroverdrive:network_flash_drive>], [<extraplanets:tier11_items>, <matteroverdrive:integration_matrix>, <extraplanets:tier11_items>]]);
recipes.addShaped(<appliedenergistics2:material:38>, [[<extraplanets:tier9_items:5>, <appliedenergistics2:material:23>, <extraplanets:tier9_items:5>],[<appliedenergistics2:material:37>, <appliedenergistics2:quartz_glass>, <appliedenergistics2:material:37>], [<extraplanets:tier9_items:5>, <appliedenergistics2:material:37>, <extraplanets:tier9_items:5>]]);
recipes.addShaped(<appliedenergistics2:material:37>, [[<extraplanets:tier7_items:5>, <appliedenergistics2:material:23>, <extraplanets:tier7_items:5>],[<appliedenergistics2:material:36>, <appliedenergistics2:quartz_glass>, <appliedenergistics2:material:36>], [<extraplanets:tier7_items:5>, <appliedenergistics2:material:36>, <extraplanets:tier7_items:5>]]);
recipes.addShaped(<appliedenergistics2:material:36>, [[<extraplanets:tier6_items:5>, <appliedenergistics2:material:23>, <extraplanets:tier6_items:5>],[<appliedenergistics2:material:35>, <appliedenergistics2:quartz_glass>, <appliedenergistics2:material:35>], [<extraplanets:tier6_items:5>, <appliedenergistics2:material:35>, <extraplanets:tier6_items:5>]]);
recipes.addShaped(<appliedenergistics2:material:35>, [[<extraplanets:tier5_items:5>, <ore:crystalPureCertusQuartz>, <extraplanets:tier5_items:5>],[<ore:crystalPureCertusQuartz>, <appliedenergistics2:material:22>, <ore:crystalPureCertusQuartz>], [<extraplanets:tier5_items:5>, <ore:crystalPureCertusQuartz>, <extraplanets:tier5_items:5>]]);
recipes.addShaped(<appliedenergistics2:controller>, [[<appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material:12>, <appliedenergistics2:smooth_sky_stone_block>],[<extraplanets:ingot_uranium>, <appliedenergistics2:material:24>, <extraplanets:tier5_items:5>], [<appliedenergistics2:smooth_sky_stone_block>, <extraplanets:tier5_items:8>, <appliedenergistics2:smooth_sky_stone_block>]]);
recipes.addShaped(<minecraft:slime_ball>, [[<minecraft:dye:2>, <minecraft:sugar>, <minecraft:dye:2>],[<minecraft:sugar>, <appliedenergistics2:material:46>, <minecraft:sugar>], [<minecraft:dye:2>, <minecraft:sugar>, <minecraft:dye:2>]]);
recipes.addShapeless(<industrialforegoing:pink_slime>, [<ore:slimeball>,<industrialforegoing:laser_lens_inverted:6>]);
recipes.addShaped(<storagenetwork:kabel> * 4, [[null, null, null],[null, <appliedenergistics2:part:140>, <galacticraftcore:basic_item:9>], [null, <galacticraftcore:basic_item:9>, null]]);
recipes.addShaped(<minestrapp:m_tech_component>, [[null, null, <minestrapp:m_gem:6>],[null, <ore:stickWood>, null], [<minestrapp:m_gem:6>, null, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_boots:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_boots>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_legings:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_legings>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_chest:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_chest>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<extraplanets:tier1_space_suit_helmet:100>, [[null, <extraplanets:tier1_armor_layer>, null],[<extraplanets:tier1_radiation_layer>, <extraplanets:tier1_un_prepared_space_suit_helmet>, <extraplanets:tier1_radiation_layer>], [null, <extraplanets:tier1_armor_layer>, null]]);
recipes.addShaped(<galacticraftcore:machine:12>, [[<ore:ingotAluminum>, <ore:itemSilicon>, <ore:ingotAluminum>],[<ore:ingotAluminum>, <minecraft:anvil>.anyDamage(), <ore:ingotAluminum>], [<minecraft:iron_ingot>, <ore:ingotCopper>, <minecraft:iron_ingot>]]);
recipes.addShaped(<galacticraftcore:basic_item:19>, [[null, null, null],[<galacticraftcore:basic_item:7>, <minecraft:repeater>, <galacticraftcore:basic_item:7>], [<deepmoblearning:soot_covered_redstone>, <minecraft:iron_ingot>, <deepmoblearning:soot_covered_redstone>]]);
recipes.addShaped(<scannable:scanner>, [[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>],[null, <galacticraftcore:basic_item:19>, null], [<minecraft:iron_ingot>, <galacticraftcore:battery:100>.anyDamage(), <minecraft:iron_ingot>]]);
recipes.addShapeless(<minecraft:cobblestone> * 2, [<galacticraftplanets:asteroids_block:*>,<galacticraftplanets:asteroids_block:*>]);
//recipes.addShaped(<storagenetwork:kabel> * 6, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:9>, null, <enderio:item_alloy_ingot:9>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
//File End
